version: "3.9"

services:
  db:
    image: postgres:16
    container_name: usv_events_db
    restart: always
    environment:
      POSTGRES_USER: usv_user
      POSTGRES_PASSWORD: usv_pass
      POSTGRES_DB: usv_events
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: usv_events_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: usv_events_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

volumes:
  postgres_data: